routes/web.php
<?php

use Illuminate\Support\Facades\Route;

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

Route::get('/', function () {
    return view('welcome');
});

Auth::routes();

Route::get('/home', 'App\Http\Controllers\HomeController@index')->name('home');

Route::group(['middleware' => 'auth'], function () {
	Route::resource('user', 'App\Http\Controllers\UserController', ['except' => ['show']]);
	Route::get('profile', ['as' => 'profile.edit', 'uses' => 'App\Http\Controllers\ProfileController@edit']);
	Route::put('profile', ['as' => 'profile.update', 'uses' => 'App\Http\Controllers\ProfileController@update']); 
	Route::put('profile/password', ['as' => 'profile.password', 'uses' => 'App\Http\Controllers\ProfileController@password']);

	//Route::resource('ingreso'     , App\Http\Controllers\IngresoController::class);
	Route::resource('paciente'    , App\Http\Controllers\PacienteController::class);
	Route::resource('medico'      , App\Http\Controllers\MedicoController::class);
	Route::resource('tipo-estudio', App\Http\Controllers\TipoEstudioController::class);

	Route::resource('paciente/{id}/ingreso'     , App\Http\Controllers\IngresoController::class);
	Route::post('paciente/{id}/ingreso/{ingreso}/upload'     ,[App\Http\Controllers\IngresoController::class, 'update']);
});


Auth::routes();

Route::get('/home', [App\Http\Controllers\HomeController::class, 'index'])->name('home');

app/Models/Paciente.php
<?php

namespace App\Models;
 
use Illuminate\Database\Eloquent\Model;

class Paciente extends Model
{ 
    protected $guarded = array('id'); 

    public function genero()
    {
        return $this->belongsTo(Genero::class, 'genero_id');    
    }

    public function municipio()
    {
        return $this->belongsTo(Municipio::class, 'municipio_id');    
    }
}

app/Http/Controllers/PacienteController.php
<?php

namespace App\Http\Controllers;

use Illuminate\Http\Request;
use App\Models\Paciente;
use App\Models\Municipio;
use App\Models\Departamento;
use App\Models\Genero;
use App\Models\Ingreso;

class PacienteController extends Controller
{
    /**
     * Display a listing of the resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function index(Request $rq)
    {
        if ($rq->ac == true) {
            $buscar = strtolower($rq->get("term"));
            $queryLike = Functions::queryLike($buscar, "LOWER(COALESCE(dpi,'') || nombre)");
            return Paciente::with('municipio')->select("id", "nombre as value")->whereRaw($queryLike)->get();
        }

        $buscar = strtolower($rq->get("buscar"));
        $queryLike = Functions::queryLike($buscar, "LOWER(COALESCE(dpi,'') || nombre)");

        $pacientes = Paciente::whereRaw($queryLike)->paginate(10);
        return view("paciente.index", compact('pacientes', 'buscar'));
    }

    /**
     * Show the form for creating a new resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function create()
    {
        $departamentos = Departamento::orderBy('nombre')->pluck('nombre', 'id');
        $municipios = Municipio::whereDepartamentoId(16)->orderBy('nombre')->pluck('nombre', 'id');
        $generos = Genero::all();
        return view('paciente.create', compact('departamentos','municipios','generos'));
    }

    /**
     * Store a newly created resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @return \Illuminate\Http\Response
     */
    public function store(Request $rq)
    {
        $paciente = new Paciente([
            'nombre' => $rq->get('nombre'),
            'correo' => $rq->get('correo'),
            'telefono' => $rq->get('telefono'),
            'genero_id' => $rq->get('genero_id'),
            'municipio_id' => $rq->get('municipio_id'),
            'dpi' => $rq->get('dpi'),
            'direccion' => $rq->get('direccion'),
            'fecha_nacimiento' => $rq->get('fecha_nacimiento'),
            'user_id' => 1,
        ]);

        $paciente->save();
        return redirect('/paciente');
    }

    /**
     * Display the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function show($id)
    {
        $paciente = Paciente::find($id);
        $ingresos = Ingreso::wherePacienteId($id)->paginate(5); 
        return view('paciente.show', compact('id', 'ingresos', 'paciente'));
    }

    /**
     * Show the form for editing the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function edit($id)
    {
        $paciente = Paciente::find($id);
        $departamentos = Departamento::orderBy('nombre')->pluck('nombre', 'id');
        $municipios = Municipio::whereDepartamentoId($paciente->municipio->departamento_id)->orderBy('nombre')->pluck('nombre', 'id');
        $generos = Genero::all();
        return view('paciente.edit', compact('paciente','departamentos','municipios','generos'));
    }

    /**
     * Update the specified resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function update(Request $rq, $id)
    {
        $paciente= Paciente::find($id);
        $paciente->nombre = $rq->get('nombre');
        $paciente->telefono = $rq->get('telefono');
        $paciente->correo = $rq->get('correo');
        $paciente->genero_id = $rq->get('genero_id');
        $paciente->municipio_id = $rq->get('municipio_id');
        $paciente->dpi = $rq->get('dpi'); 
        $paciente->direccion = $rq->get('direccion');
        $paciente->fecha_nacimiento = $rq->get('fecha_nacimiento');
        $paciente->save();
        
        return redirect('/paciente');
    }

    /**
     * Remove the specified resource from storage.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function destroy($id)
    {
        //
    }
}

resources/views/paciente/create.blade.php
@extends('layouts.app', ['title' => __('User Profile')])

@section('content')
@include('layouts.headers.empty')
    <div class="container-fluid mt--7">
        <div class="row">
            <div class="col-xl-3"></div>
            <div class="col-xl-6 ">
                <div class="card bg-secondary shadow">
                    <div class="card-header bg-white border-0">
                        <div class="row align-items-center">
                            <h3 class="mb-0">{{ __('Registrar Paciente') }}</h3>
                        </div>
                    </div>
                    <div class="card-body">
                        <form method="post" action="{{ route('paciente.store') }}" autocomplete="off">
                            @csrf
                            <div class="pl-lg-4">

                                <div class="form-group{{ $errors->has('dpi') ? ' has-danger' : '' }}">
                                    <label class="form-control-label" for="input-name">{{ __('DPI - formato (NNNN NNNNN NNNN)') }}</label>
                                    <input type="text" v-model="dpi" v-on:keyup="formatOnlyNumbers()" name="dpi" class="numeric form-control" placeholder="DPI" required >
                                </div> 
                                
                                <div class="form-group{{ $errors->has('nombre') ? ' has-danger' : '' }}">
                                    <label class="form-control-label" for="input-name">{{ __('Nombre') }}</label>
                                    <input type="text" name="nombre"  class="form-control" placeholder="nombre" required >
                                </div>
                                <div class="form-group{{ $errors->has('departamento_id') ? ' has-danger' : '' }}">
                                    <label class="form-control-label" for="input-name">{{ __('Municipio') }}</label>
                                    {{ Form::select('departamento_id', $departamentos, 16, ['class' => 'form-control']) }}
                                </div> 


                                <div class="form-group{{ $errors->has('municipio_id') ? ' has-danger' : '' }}">
                                    <label class="form-control-label" for="input-name">{{ __('Municipio') }}</label>
                                    {{ Form::select('municipio_id', $municipios, 1, ['class' => 'form-control']) }}
                                </div> 
                                

                                <div class="form-group{{ $errors->has('genero_id') ? ' has-danger' : '' }}">
                                    <label class="form-control-label" for="input-name">{{ __('Genero') }}</label>
                                    <select name="genero_id" id="" class="form-control">
                                        <option>seleccionar</option>
                                          @foreach ($generos as $g)
                                             <option value="{{$g->id}}">
                                               {{$g->nombre}}
                                            </option>
                                           @endforeach
                                    </select>
                                </div>


                                <div class="form-group{{ $errors->has('fecha_nacimiento') ? ' has-danger' : '' }}">
                                    <label class="form-control-label" for="input-name">{{ __('Fecha Nacimiento') }}</label>
                                    <input type="date" name="fecha_nacimiento" class="form-control" placeholder="fecha nacimiento" required >
                                </div>
                                <div class="form-group{{ $errors->has('correo') ? ' has-danger' : '' }}">
                                    <label class="form-control-label" for="input-name">{{ __('Correo') }}</label>
                                    <input type="text" name="correo" class="form-control" placeholder="correo" >
                                </div>
                                <div class="form-group{{ $errors->has('telefono') ? ' has-danger' : '' }}">
                                    <label class="form-control-label" for="input-name">{{ __('Telefono') }}</label>
                                    <input type="text" name="telefono"  class="form-control" placeholder="telefono" >
                                </div> 
                                <div class="form-group{{ $errors->has('direccion') ? ' has-danger' : '' }}">
                                    <label class="form-control-label" for="input-name">{{ __('Direccion') }}</label>
                                    <input type="text" name="direccion" class="form-control" placeholder="direccion" required >
                                </div>
                                <div class="text-center">
                                    <button type="submit" v-bind:disabled="habilitarEnvio(dpi)" class="btn btn-success mt-4">{{ __('Guardar') }}</button>
                                </div>
                            </div>
                        </form>
                    </div>
                </div>
            </div>
            <div class="col-xl-3"></div>
        </div>
        
        @include('layouts.footers.auth')
    </div>
@endsection
@push('js')
   <script> 
         $('select[name=departamento_id]').change(function() {
            fetch("/api/municipios/" + $(this).val())
                .then(data => data.json())
                .then(json => {
                    let options = "";
                    json.forEach(municipio => {
                        options += '<option value="' + municipio.id + '">' + municipio.nombre + '</option>';
                    });
                    $('select[name=municipio_id]').html(options);
                })
                .catch(err => console.log(err))
        })

   </script>
@endpush

resources/views/paciente/edit.blade.php
@extends('layouts.app', ['title' => __('User Profile')])

@section('content')
@include('layouts.headers.empty')
     <div class="container-fluid mt--7">
        <div class="row">
            <div class="col-xl-3"></div>
            <div class="col-xl-6 ">
                <div class="card bg-secondary shadow">
                    <div class="card-header bg-white border-0">
                        <div class="row align-items-center">
                            <h3 class="mb-0">{{ __('Registrar Paciente') }}</h3>
                        </div>
                    </div>
                    <div class="card-body">
                        <form method="post" action="{{ route('paciente.update', $paciente->id) }}" autocomplete="off">
                            @method('PATCH')
                            @csrf
                            <div class="pl-lg-4">

                                <div class="form-group{{ $errors->has('paciente') ? ' has-danger' : '' }}">
                                    <label class="form-control-label" for="input-name">{{ __('DPI') }}</label>
                                    <input type="text" name="dpi" value="{{$paciente->dpi}}" class="form-control" placeholder="DPI" required >
                                </div> 

                                <div class="form-group{{ $errors->has('paciente') ? ' has-danger' : '' }}">
                                    <label class="form-control-label" for="input-name">{{ __('Nombre') }}</label>
                                    <input type="text" name="nombre" value="{{$paciente->nombre}}"  class="form-control" placeholder="nombre" required >
                                </div> 

                                <div class="form-group{{ $errors->has('departamento_id') ? ' has-danger' : '' }}">
                                    <label class="form-control-label" for="input-name">{{ __('Municipio') }}</label>
                                    {{ Form::select('departamento_id', $departamentos, $paciente->municipio->departamento_id, ['class' => 'form-control']) }}
                                </div> 


                                <div class="form-group{{ $errors->has('municipio_id') ? ' has-danger' : '' }}">
                                    <label class="form-control-label" for="input-name">{{ __('Municipio') }}</label>
                                    {{ Form::select('municipio_id', $municipios, $paciente->municipio_id, ['class' => 'form-control']) }}
                                </div> 
                                

                                <div class="form-group{{ $errors->has('name') ? ' has-danger' : '' }}">
                                    <label class="form-control-label" for="input-name">{{ __('Genero') }}</label>
                                    <select name="genero_id" id="" class="form-control">
                                        <option>seleccionar</option>
                                          @foreach ($generos as $g)
                                             <option value="{{$g->id}}" {{($paciente->genero_id == $g->id? 'selected': '') }}>
                                               {{$g->nombre}}
                                            </option>
                                           @endforeach
                                    </select>
                                </div>
                                <div class="form-group{{ $errors->has('paciente') ? ' has-danger' : '' }}">
                                    <label class="form-control-label" for="input-name">{{ __('Fecha Nacimiento') }}</label>
                                    <input type="date" name="fecha_nacimiento" value="{{$paciente->fecha_nacimiento}}" class="form-control" placeholder="fecha nacimiento" required >
                                </div>
                                <div class="form-group{{ $errors->has('paciente') ? ' has-danger' : '' }}">
                                    <label class="form-control-label" for="input-name">{{ __('Correo') }}</label>
                                    <input type="text" name="correo" value="{{$paciente->correo}}" class="form-control"  placeholder="correo" required >
                                </div>
                                <div class="form-group{{ $errors->has('paciente') ? ' has-danger' : '' }}">
                                    <label class="form-control-label" for="input-name">{{ __('Telefono') }}</label>
                                    <input type="text" name="telefono" value="{{$paciente->telefono}}" class="form-control" placeholder="telefono" required >
                                </div>
                                <div class="form-group{{ $errors->has('paciente') ? ' has-danger' : '' }}">
                                    <label class="form-control-label" for="input-name">{{ __('Direccion') }}</label>
                                    <input type="text" name="direccion" value="{{$paciente->direccion}}" class="form-control" placeholder="direccion" required >
                                </div>
                                <div class="text-center">
                                    <button type="submit" class="btn btn-success mt-4">{{ __('Guardar') }}</button>
                                </div>
                            </div>
                        </form>
                    </div>
                </div>
            </div>
            <div class="col-xl-3"></div>
        </div>
        
        @include('layouts.footers.auth')
    </div>
@endsection

@push('js')
   <script>
        $('select[name=departamento_id]').change(function() {
            fetch("/api/municipios/" + $(this).val())
                .then(data => data.json())
                .then(json => {
                    let options = "";
                    json.forEach(municipio => {
                        options += '<option value="' + municipio.id + '">' + municipio.nombre + '</option>';
                    });
                    $('select[name=municipio_id]').html(options);
                })
                .catch(err => console.log(err))
        })

   </script>
@endpush

resources/views/paciente/index.blade.php
@extends('layouts.app')


@push('css')
<style>
    .paginacion  svg {
        width: 25px;
    }
    
    .paginacion > nav > div > a {
        display: none;
    } 
    
    .paginacion > nav > div > span {
        display: none;
    }
</style>
@endpush
@section('content')
    @include('layouts.headers.empty')

    <div class="container-fluid mt--8">
        <div class="row">
            <div class="col ">
                <div class="card shadow">
                    <div class="card-header border-0">
                        <div class="row align-items-center">
                          <div class="col-8">
                            <h3 class="mb-0">Listado de pacientes</h3>
                        </div>
                        <div class="col-4 text-right">
                            <a href="/paciente/create" class="btn btn-sm btn-primary">Agregar paciente</a>
                        </div>
                        </div>
                    </div>
                    <!-- Light table -->
                    <div class="table-responsive">
                        <table class="table align-items-center table-flush">
                            <thead class="thead-light">
                                <tr>
                                    <th scope="col" class="sort" data-sort="name">ID</th>
                                    <th scope="col" class="sort" data-sort="name">Nombre</th>
                                    <th scope="col" class="sort" data-sort="budget">Correo</th>
                                    <th scope="col" class="sort" data-sort="status">Telefono</th>
                                    <th scope="col" class="sort" data-sort="status">DPI</th> 
                                    <th scope="col" class="sort" data-sort="status">Fecha Nacimiento</th>
                                    <th scope="col" class="sort" data-sort="status">Direccion</th>
                                    <th scope="col" class="sort" data-sort="status">Editar</th>
                                </tr>
                            </thead>
                            <tbody class="list">
                                @foreach ($pacientes ?? '' as $p)
                                    <tr>
                                        <td> {{ $p->id }} </td>
                                        <td> {{ $p->nombre }} </td>
                                        <td> {{ $p->correo }} </td>
                                        <td> {{ $p->telefono }} </td>
                                        <td> {{ $p->dpi }} </td> 
                                        <td> {{ $p->fecha_nacimiento }} </td>
                                        <td> {{ $p->direccion }} </td>
                                        <td> 
                                            <a href="/paciente/{{$p->id}}/edit" class="mx-1">
                                                <i class="fas fa-edit" title="Editar paciente"></i>
                                            </a>

                                            <a href="/paciente/{{$p->id}}" class="mx-1">
                                                <i class="fas fa-eye" title="Editar paciente"></i>
                                            </a>
                                        </td>
                                    </tr>
                                @endforeach
                            </tbody>

                        </table>

                    </div>
                    <!-- Card footer -->
                    <div class="card-footer py-4 paginacion"> 
                        {{ $pacientes->appends(['buscar' => $buscar ])->links() }}
                    </div>
                </div>
            </div>
        </div>

        @include('layouts.footers.auth')
    </div>
@endsection